#!/bin/bash

g++ -Iinclude src/yaud.cpp -o yaud && g++ -Iinclude src/dd.cpp -o dd && g++ -Iinclude src/rm.cpp -o rm && g++ -Iinclude src/umount.cpp -o umount && g++ -Iinclude src/mkfs.cpp -o mkfs && g++ -Iinclude src/installer.cpp -o installer

sudo ./installer
